on:
  workflow_dispatch:
  push:
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive symcc
    - run: docker build -t symcc symcc
    - run: docker build -t symqemu .
