on:
  workflow_dispatch:
  push:
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive symcc
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: symcc
        cache-from: type=gha
        cache-to: type=gha
    - uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        cache-to: type=gha
